### PR TITLE
[Fix] Modal will close on error

### LINKED ISSUE #1361: Visibility setting is present even with errors
**Describe the bug**
I have noticed this will creatin a new profile that when you change something and save the visibility settings would be presented even with an error. These settings should only be presented once there are no errors.

**To Reproduce**

**Expected behavior**

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by Rizvida1**
#### Changes introduced

The modal will close when an error appears.

#### Related issue(s)

Fixes #1361

### CODE REVIEW

**Comment by mo-5** [comment]
Should the modal even come up there is an error ? can you make it only come up if their profile is actually ready to be saved. Otherwise its not practical to present it since they will get it again after they fix the error. Do you know what I mean.

**Comment by Rizvida1** [comment]
> Should the modal even come up there is an error ? can you make it only come up if their profile is actually ready to be saved. Otherwise its not practical to present it since they will get it again after they fix the error. Do you know what I mean.

The issue is that the form is validated upon submitting. So to do that, well have to create a separate form validation from the submission.

**Comment by mo-5** [comment]
> > Should the modal even come up there is an error ? can you make it only come up if their profile is actually ready to be saved. Otherwise its not practical to present it since they will get it again after they fix the error. Do you know what I mean.
> 
> The issue is that the form is validated upon submitting. So to do that, well have to create a separate form validation from the submission.

Ah I see what you mean. I think we should leave it as is then since closing it immediately might cause more confusion. I will close the ticket. Sorry about that

**Comment by Rizvida1** [comment]
> > > Should the modal even come up there is an error ? can you make it only come up if their profile is actually ready to be saved. Otherwise its not practical to present it since they will get it again after they fix the error. Do you know what I mean.
> > 
> > 
> > The issue is that the form is validated upon submitting. So to do that, well have to create a separate form validation from the submission.
> 
> Ah I see what you mean. I think we should leave it as is then since closing it immediately might cause more confusion. I will close the ticket. Sorry about that

I actually think this makes sense to leave in because it is more confusing if the modal stays open rather than return to the form. That way they can probably see the error.

**Review by mo-5 — APPROVED** [review]

**Pull request merged**
