### PR TITLE
[Feat] Allow user to report bugs

### LINKED ISSUE #959: Feedback from users
**Is your feature request related to a problem? Please describe.**
Adding a small feedback system in the application could be beneficial, when the user wants to report a bug or has some suggestions for the application

**Describe the solution you'd like**
Somewhere to put some text like a comment (maybe in the footer, or in the dropdown, or on the logged in home page), it would automatically link the comment to that user, we would see it in the admin dashboard and we could triage it later on

### PR DESCRIPTION
**Pull request by BenJeau**
#### Changes introduced

This PR adds bug tracking feature to let users report bugs, a bug
- has created/updated at times
- has a status either `duplicate` or `resolved` or `unresolved`
- has a location of either `home` or `search` or `profile` or `forms` (for easier sorting in the admin dash)
- has a description
- has a linked user
- can have an application version (this is optional right now, since I'm not sure how to get the tag of the docker image inside the container)
- can have a linked GitHub issue

Details of this PR
- Add button to report bugs in the footer
- The bug is linked to the user and the user is shown a modal with some fields to enter
- The admin dashboard can see the bugs and update its status

#### Related issue(s)

closes #959

#### Screenshots (if applicable)

In the footer and accessible from any page
image

Only visible when logged in:
image

The modal that shows up when clicking on the button
image

Admin dash table
image

Admins dash edit popup
image

#### Checklist
If the database has been modified:
- [x] Update database diagram 
- [x] Create new migration 

If API endpoints has been modified:
- [x] Update backend documentation 
- [x] Create/Update validators for the API endpoints 
- [x] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [x] The modifications are tab friendly
- [x] It is accessible

### CODE REVIEW

**Comment by mo-5** [comment]
I am not sure if it's just me but shouldn't all the buttons on the footer match ?

**Comment by BenJeau** [comment]
Yeah, I'm not sure yet about that. I just think it should somehow be different from the others, since the other links just redirect to the about pages. Should it just be in the dropdown?

Here's a few different options for the Footer, 
image
image

or in the dropdown
image

**Comment by BenJeau** [comment]
Just need to extract the strings from the frontend and cleanup a bit the components (to be like the other and to respect the view/controller distinction)

**Comment by BenJeau** [comment]
The only thing that I was not able to accomplish is getting the application version, aka the tag/name of the docker image

**Comment by BenJeau** [comment]
@dynamic11 what is your opinion on the button in the footer?

**Review by mo-5 — APPROVED** [review]

**Comment by BenJeau** [comment]
I just pushed a commit that adds a "Duplicate" status for a bug, in case a bug already exists

**Pull request merged**
