### PR TITLE
[Feat] Create pull_request_template.md

### PR DESCRIPTION
**Pull request by BenJeau**

### CODE REVIEW

**Comment by mo-5** [comment]
Maybe add for UI to check IE 11

**Review by mo-5 — APPROVED** [review]

**Comment by mo-5** [comment]
Sorry another thing, Could you add the i18 commands?  like run i18n:check and i18n:cleanup

**Comment by BenJeau** [comment]
> Sorry another thing, Could you add the i18 commands? like run i18n:check and i18n:cleanup

@MohamedRadwan Should I add it as a comment in the file?

**Comment by mo-5** [comment]
Yeah, I think as a comment next to both language so developers don't forget to run them.

**Pull request merged**
