### PR TITLE
[Update] My circle heading

### LINKED ISSUE #1599: In user profile, next to My Circle heading, remove tooltip and change subheading to instructional text
Current view
image

1. Remove tool tip (i) (connections.tooltip.header)  next to Header  
And 
2. Replace sub heading "My Circle" with the following text:

EN: Colleagues with elevated viewing privileges to your profile
FR: Des collègues avec des privilèges d'affichage élevés à votre profil

Under Sub-heading add the following instructions:
EN: To add or remove colleagues, search their profiles and click on "Add to My Circle" or "Remove from My Circle"
FR: Pour ajouter ou retirer des collègues, cherchez leurs profils et cliquez sur « Ajouter à Mon Cercle » ou « Retirer de Mon Cercle »

### PR DESCRIPTION
**Pull request by mo-5**
#### ⭐ Changes introduced

Update the my circle section and removed the tooltip along with changing the subheading. 

#### 🔗 Related issue(s)

closes #1599

#### 📸 Screenshots (if applicable)
image
image

#### ☑️ Checklist

If the database has been modified:

- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:

- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak

If the UI has been modified:

- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:

- [ ] run `yarn i18n:validate" and clear errors

### CODE REVIEW

**Comment by dynamic11** [comment]
what about this?
image
image

**Comment by dynamic11** [comment]
with additional space:
image

**Comment by dynamic11** [comment]
what do you guys think about this?
image

**Review by mo-5 — COMMENTED** [review]
LGTM

**Comment by MenaMachado** [comment]
Looks good to me too

**Comment by dynamic11** [comment]
#1624 addresses this fix

**Pull request closed without merging**
