### PR TITLE
[Fix] Remove select all option for Skills and Mentorship Skills dropdowns

### LINKED ISSUE #1127: Remove select all option in tree select dropdowns
⚠️ **based on user testing**
- users don't understand that each category name in the tree select has a dropdown so they click the name of the category and it auto selects all items under it

ℹ️ **I propose**
- we remove the select all option

### PR DESCRIPTION
**Pull request by Mousto097**
⭐  **Changes introduced**
- Removed select all option for Skills and Mentorship Skills dropdowns in SearchFilter and SearchBar
- Set `selectable: false,`, `checkable: false,` and `disableCheckbox: true, ` for all parent nodes in dataTree
- updated antd to 4.9.4 as it contains `TreeSelect` updates
- prevent forms from submitting on 'enter' keypress

ℹ️  **Related issue(s)**
- Closes #1127

### CODE REVIEW

**Comment by SukhsimranpreetSekhon** [comment]
Also need to fix: after selecting option value (example: "Specialization: Politics") and pressing the "enter" key, it will refresh the page instead of selecting the content.

**Comment by SukhsimranpreetSekhon** [comment]
Also need to fix: category should not be a selectable/checkable item.

**Comment by SukhsimranpreetSekhon** [comment]
> Also need to fix: category should not be a selectable/checkable item.

Maybe we can use the "disabled" prop to disable the category name from being selected.

**Comment by SukhsimranpreetSekhon** [comment]
> Also need to fix: after selecting option value (example: "Specialization: Politics") and pressing the "enter" key, it will refresh the page instead of selecting the content.

Have to fix it up using the "onSelect" prop or there is something wrong with the form and form.item components sending the selected data through right away once the "enter" key is pressed.

**Comment by dynamic11** [comment]
🐞 BUG FOUND:
on the advance search if you try to use the keyboard to select a skill and hit enter to make selection the form submits.

**Comment by dynamic11** [comment]
Found the fix I think!
will push fix shortly! 🥳

**Comment by dynamic11** [comment]
more fixes are coming! i need to update the rest

**Comment by mo-5** [comment]
Is this pr ready for review?

**Comment by dynamic11** [comment]
Yes it is 😁

**Review by mo-5 — APPROVED** [review]

**Comment by mo-5** [comment]
Looks good

**Pull request merged**
