### PR TITLE
[Feat] Improved testing and added many tests (62% code coverage)

### PR DESCRIPTION
**Pull request by BenJeau**
#### Changes introduced

> **Note:** This PR depends on this [PR](https://github.com/SectorLabs/keycloak-mock/pull/7) of `keycloack-mock` to properly test keycloak roles. Meanwhile I'm pointing the version to be the one of my fork, which should work

This PR adds a total of 552 tests (there were only 52 before), all there's left to test endpoint wise after this PR are these 5

- GET `/api/search/filters`
- GET `/api/search/fuzzy`
- GET `/api/profile/:id`
- PUT `/api/profile/:id`
- GET `/api/profile/private/:id`

____

- Added correct keycloak mocking
  - Added role support and role related tests
- Added tests for
  - GET, POST, DELETE `/api/connections`
  - GET, POST, PUT `/api/bugs`
  - GET, POST, DELETE `/api/user`
  - GET `/api/keycloak/users`
  - GET `/api/profGen`
  - GET `/api/option/branches`
  - GET `/api/option/careerMobilities`
  - GET `/api/option/cityLocations`
  - GET `/api/option/classifications`
  - GET `/api/option/lookingJobs`
  - GET `/api/option/securityClearances`
  - GET `/api/option/talentMatrixResults`
  - GET `/api/option/tenures`
  - GET `/api/option/developmentalGoals`
  - GET `/api/stats/topFiveSkills`
  - GET `/api/stats/growthRateByMonth`
  - GET `/api/stats/growthRateByWeek`
  - ... all of the options and stats endpoints
- Removed the need for specifying ID for POST, GET for `/api/user`, since the ID is the same as keycloak's ID
- Use proper HTTP status codes, since our POST, DELETE, and PUT don't return content
  - `201` for POST
  - `204` for DELETE and PUT

#### Related issue(s)

#234

#### Screenshots (if applicable)

Before this PR:
image

This PR:
image

#### Checklist
If API endpoints has been modified:
- [ ] Update backend documentation 
- [x] Create/Update validators for the API endpoints 
- [x] The API endpoints are properly secured with keycloak

### CODE REVIEW

**Comment by BenJeau** [comment]
> TODO: Update frontend API calls to user endpoint (before I forget)

**Comment by dynamic11** [comment]
wow great work!

**Comment by BenJeau** [comment]
@dynamic11 or @MohamedRadwan is this PR good to go (aside from the conflict)? I just think we should merge it as soon as possible to not get some kind of regression in the backend, if we modify the backend

**Review by mo-5 — APPROVED** [review]
Yes, this looks good. Do you think you could update the ticket with what's left to do?

**Comment by BenJeau** [comment]
Yes, I will do so, I have a plan in mind on how to get 100% code coverage in the backend, I'll write it in the issue, in case I don't have enough time to tackle all of the rest

**Pull request merged**
