### PR TITLE
[Fix] Improved tabbing

### LINKED ISSUE #924: Tabbing not working in profile forms
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by BenJeau**
#### Changes introduced

- Darken the input fields focus color
- Removed the border previously used for the focusing
- Links are now underlined and look more like links
- Buttons have the same effect as input fields for focusing
- I-talent focus is rounded
- Focus in the navbar is white
- Made Popups (tooltips) tabbable
- Made admin sidebar tabbable
- Updated the "focus" of checkboxes to be the same as input fields
- Fixed the tabbing look for the create flow sidebar menu items
- Fixed tabbing for skills/comp/devGoals section in profiles

#### Related issue(s)

fixes #924

#### Screenshots (if applicable)

Before:
Peek 2020-10-05 15-291

This PR:
Peek 2020-10-06 15-48

#### Checklist
If the UI has been modified:
- [ ] Has been tested on IE (@dynamic11 could you test this for me?)
- [x] The modifications are tab friendly (for sure hahaha)
- [ ] It is accessible (hopefully)

### CODE REVIEW

**Comment by BenJeau** [comment]
This for sure conflicts with #890, hope #890 merges before

**Comment by BenJeau** [comment]
I tested this on Ubuntu Chrome and Firefox - hope it works on IE - @dynamic11 can you test it for me?

**Comment by dynamic11** [comment]
tested in IE not working

**Review by dynamic11 — CHANGES_REQUESTED** [review]
Change is not working in IE. Tabbing is now showing up. App is also extremely laggy in IE

**Comment by BenJeau** [comment]
Will fix the tabbing for IE

**Comment by BenJeau** [comment]
The tabbing itself seems to work, its just the scss that IE doesn't like

**Comment by BenJeau** [comment]
@dynamic11 should be good now - not sure since I can't login into the app from Windows. I just needed to convert any hex that had an alpha value to rgba since IE doesn't support that and needed to separate all the css selectors, IE didn't like the commas separating them

**Review by dynamic11 — APPROVED** [review]
great!

**Pull request merged**
