### PR TITLE
[New] Move from lodash to lodash-es and change the import 

### LINKED ISSUE #633: Change Lodash to Lodash-es  Frontend
Lodash-es is a much smaller package than lodash. It has been exported to es modules. It can be found in the following link. 
https://www.npmjs.com/package/lodash-es

This can improve the performance and load time for backend and frontend. 

Size difference 1.4 MB (Lodash) and 629 kB (Lodash-es) 

Let me know what you guys think about this change if you see any issues with this change.

### PR DESCRIPTION
**Pull request by mo-5**
The best way to import lodash in react is by a component that we will use for example: 

import {map} from "lodash-es"; 

this will improve the speed of the application since we won't need to import the whole library for one method.

closes #633

### CODE REVIEW

**Review by BenJeau — APPROVED** [review]
Looks good, you'll just need to update two other imports

**Comment by mo-5** [comment]
> Looks good, you'll just need to update two other imports

Which imports?

**Comment by mo-5** [comment]
oh nevermind I see

**Comment by mo-5** [comment]
I found that there are unclosed issues with lodash-es that break some functionality so I moved back to lodash but with the new way of importing by use methods

**Pull request merged**
