### PR TITLE
[Fix] Remove date picker

### LINKED ISSUE #1300: Remove Date Picker for Official languages Expiry Dates and replace with drop down menu
Task: Remove Date picker and replace with a dropdown list for OL status with Valid, Expired, Unknown, N/A

Given a user is in the edit profile page, Official languages changes
When they toggle switch to yes for "Do you have a second language results?"
They must enter their results for Reading, Writing, and Oral.
They can enter A, B, C, E, X, or N/A for Reading, Writing, and Oral. 

Acceptance Criteria 1
When a user enters the language result: A, B, or C
Then they will be able to select Expired, Valid, Unknown from the drop down list
and 
Then the user's profile will display the selected result and status in the profile e.g B (expired) or C (valid)

Acceptance Criteria 2
When a user enters the language result: E, X, or N/A
Then the OL status will default to N/A
and 
Then the user's profile will display the selected result E, X, or N/A

Display (valid or expired) next to result in the view profile.

image

image

### PR DESCRIPTION
**Pull request by mo-5**
#### Changes introduced

This pr removes the data picker from the official languages section and used "valid", "expired", "Unkown" instead.

#### Related issue(s)

closes #1300

#### Screenshots (if applicable)

image
image
image
image
image
image

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Review by Rizvida1 — CHANGES_REQUESTED** [review]
Setting the results to N/A causes empty brackets to appear.
image

image

**Comment by mo-5** [comment]
> Setting the results to N/A causes empty brackets to appear.
> image
> 
> image

Good catch. Fixed

**Review by Rizvida1 — CHANGES_REQUESTED** [review]
Are you sure the issue is fixed because I'm still getting the empty brackets.

**Comment by mo-5** [comment]
> Are you sure the issue is fixed because I'm still getting the empty brackets.

You are right I forgot to push. My bad. Should be good now

**Review by Rizvida1 — APPROVED** [review]
Good stuff

**Pull request merged**
