### PR TITLE
[New] Add webpack analyzer

### PR DESCRIPTION
**Pull request by dynamic11**
#### Changes introduced
- Add webpack analyzer to see the contents and size of webpack
- run 'yarn analyze' to run the analyzer
- visit localhost:3031 to see the visualization

#### Screenshots (if applicable)
this is a screenshot of the analyzer
image

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Review by BenJeau — APPROVED** [review]

**Review by BenJeau — CHANGES_REQUESTED** [review]
It's failing in Jenkins for some reason - seems related to this change - you may need to add it to the deps and not devDeps, not sure image

**Comment by dynamic11** [comment]
> It's failing in Jenkins for some reason - seems related to this change - you may need to add it to the deps and not devDeps, 

hmmmm.....you are right I forgot that the razzle plugin is also there for prod. Let me think of a solution. (i really don't think we should have it in production...let me know what you think) 

@BenJeau if you have any idea on how to have "development only" plugins let me know. I can't seem to find it in the documentation

**Comment by BenJeau** [comment]
@dynamic11 not sure, but I have a feeling it doesn't matter if we just put it in the deps instead of devDeps, I don't think it has an influence on the react bundle size, just our docker image will be slightly bigger

**Comment by BenJeau** [comment]
For reference, I tried reducing the size of antd.less with https://github.com/ant-design/babel-plugin-import, with no success, maybe others will be able to do it

**Review by BenJeau — APPROVED** [review]
Sorry, forgot about this PR - was waiting to see if it builds successfully on Jenkins - LGTM :+1:

**Comment by dynamic11** [comment]
snyk is now failing

**Comment by BenJeau** [comment]
mhh, should we merge it still?

**Pull request merged**
