### PR TITLE
[New] Add college list

### LINKED ISSUE #990: Update the list of schools in the tables to include colleges
**Describe the bug**
The current list only had universities for the dropdown list used for schools when users complete their profiles under Education. 

Here's the link to our ITalent team channel for the list of schools

  https://033gc.sharepoint.com/:x:/r/sites/I-Talent-I-TalentMenaandcurrentdevelopers/Shared%20Documents/I-Talent%20(Mena%20and%20current%20developers)/Data%20lists/List%20of%20translated%20schools%20update%20Oct%2023.xlsx?d=w020b56dd2387403084b98a3d28d8f9e0&csf=1&web=1&e=fUjmAb

### PR DESCRIPTION
**Pull request by mo-5**
#### Related issue(s)

closes #990

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by BenJeau** [comment]
A small note here, we'll need to do the seeding in the our instances - @MohamedRadwan and @dynamic11 do we want the seeding to happen automatic? (so we don't forget in the future) If so, we just need to add `yarn -s seed` after the migration to this package.json script 

https://github.com/CDH-Studio/I-Talent/blob/69f274429f5f69b1f3db78715c74117d3d3b1ebd/services/backend/package.json#L13

**Review by BenJeau — APPROVED** [review]
Looks good, just the small comment above

**Review by BenJeau — CHANGES_REQUESTED** [review]
Just saw you duplicated the translations in the seed data, I would recommend to not do that, like its done here https://github.com/CDH-Studio/I-Talent/blob/development/services/backend/src/database/seeds/20200610114410-init-options/data/schools.js#L1

**Comment by mo-5** [comment]
> A small note here, we'll need to do the seeding in the our instances - @MohamedRadwan and @dynamic11 do we want the seeding to happen automatic? (so we don't forget in the future) If so, we just need to add `yarn -s seed` after the migration to this package.json script
> 
> https://github.com/CDH-Studio/I-Talent/blob/69f274429f5f69b1f3db78715c74117d3d3b1ebd/services/backend/package.json#L13

Yeah I think keeping it automatic might be a good idea

**Comment by mo-5** [comment]
> Just saw you duplicated the translations in the seed data, I would recommend to not do that, like its done here https://github.com/CDH-Studio/I-Talent/blob/development/services/backend/src/database/seeds/20200610114410-init-options/data/schools.js#L1

Its duplicate because the university seed before this removes the original seed

**Comment by BenJeau** [comment]
Oh, I don't think we're talking about the same thing. I mean you are specifying the same thing for the French and English translations, in the init seed, it was only specified in the specific language, and was specified in the other if there would be a difference in the writing between language

**Comment by BenJeau** [comment]
and to make the seeding automatic, feel free to add it to the package.json

**Comment by mo-5** [comment]
Oh I see what you mean. Yeah, I am not sure I just copy-pasted the excel file that I was given and both English and French have the same name. We could put them in one field I guess.

**Comment by BenJeau** [comment]
I would accept it, but should the translations only be in the specified language? (I feel like it does, but if you think otherwise, I'll accept the PR)

**Comment by mo-5** [comment]
Wait sorry I don't understand what you mean ? So for example you want me to leave french empty and only insert them in English ?

**Comment by BenJeau** [comment]
Yes, just so we don't have duplicate information in the database, in case they would like to update one name, they would only need to update the english one and not both

**Comment by mo-5** [comment]
Yeah I could just add one. I will check with mena since the document they provided had an English and French and they were both the same. So they wanted to add the same name for both English and French.

**Comment by BenJeau** [comment]
Oh ok, the backend of the app is made so that it returns the English value if the French is not defined and vice-versa. I guess that is something that can be added as a notice on the admin dashboard for when people modify/add schools

**Comment by mo-5** [comment]
I am waiting to check with mena. However from the list that I was provided it seems like they wanted the same name stored in both English and French but I will double check: 

https://033gc.sharepoint.com/:x:/r/sites/I-Talent-I-TalentMenaandcurrentdevelopers/Shared%20Documents/I-Talent%20(Mena%20and%20current%20developers)/Data%20lists/List%20of%20translated%20schools%20update%20Oct%2023.xlsx?d=w020b56dd2387403084b98a3d28d8f9e0&csf=1&web=1&e=fUjmAb

**Review by BenJeau — APPROVED** [review]

**Pull request merged**
