### PR TITLE
[Feat] Added linting checks

### LINKED ISSUE #228: Github action to auto run linting
**Is your feature request related to a problem? Please describe.**
Set up a method (possibly with github actions) to run/test linting issues on fresh PRs 

**Describe the solution you'd like**
My work flow should be (as discussed):
1. I make changes to my branch
2. I run linter locally to clean up changes
3. Open PR
4. Automatic system catches linting issue
5. I fix issues and update PR
6. merge

### PR DESCRIPTION
**Pull request by BenJeau**
Added Github Actions for linting the code in Github, will also add https://www.npmjs.com/package/pre-commit, but can't until #227 is finished since it won't let me commit without fixing all of the eslint errors :laughing: 

closes #228

### CODE REVIEW

**Comment by dynamic11** [comment]
what is the status of this PR?

**Comment by BenJeau** [comment]
Just talked to Mohammed for the backend, since the check is not passing. He's fixing them as we speak. We can merge this and just make the backend check optional until they are fixed

**Comment by BenJeau** [comment]
I think for now having the linter check in GitHub is good enough, unless we still want to add the pre-commit hook. (the only downfall is that it will lint the whole project each time you commit locally, which can take a couple of seconds, ~5-10 secs). @dynamic11 what do you think?

**Comment by dynamic11** [comment]
> I think for now having the linter check in GitHub is good enough, unless we still want to add the pre-commit hook. (the only downfall is that it will lint the whole project each time you commit locally, which can take a couple of seconds, ~5-10 secs). @dynamic11 what do you think?

I agree

**Review by dynamic11 — APPROVED** [review]

**Comment by dynamic11** [comment]
We know that backend lint is failing. A fix is in the works for a future PR.

**Pull request merged**
