### PR TITLE
[Fix] Update frontend packages

### PR DESCRIPTION
**Pull request by mo-5**
#### ☑️ Checklist

If the database has been modified:

- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:

- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak

If the UI has been modified:

- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:

- [ ] run `yarn i18n:validate" and clear errors

### CODE REVIEW

**Review by dynamic11 — CHANGES_REQUESTED** [review]
this seems to have broken the date pickers :(

**Comment by mo-5** [comment]
Reverted the update to day js please take another look and see if there is still an issue

**Comment by dynamic11** [comment]
when i click to open date picker its still crashing for some reason 😕 
@Rizvida1 can you try this aswell?

**Comment by mo-5** [comment]
Let me double check again because I am not having that issue. I will delete my container and reinstall

**Comment by mo-5** [comment]
@dynamic11 Do you mind posting which date picker crashes ? because I have updated everything including dayjs but it doesn't crash on my side

**Comment by dynamic11** [comment]
it was the education one for me

**Comment by dynamic11** [comment]
I retested this and it seems to be working. my bad 💯

**Review by dynamic11 — APPROVED** [review]

**Pull request merged**
