### PR TITLE
Changed title for other's profiles

### LINKED ISSUE #188: "My Profile" header displayed on other users' profiles
**Describe the bug**
When on a user's profile page that isnt one's own profile page/account, the profile page shows a header called "My Profile"

**To Reproduce**
1. Go to any user's profile that isnt your own
2. View header at top of user's profile, should say "My Header"

**Expected behavior**
Header should show [other user's name]'s Profile not "My Profile". 
Ex: If I (Kate Thornley) view Rizvi's profile, his header should say "Rizvi's Profile"

**Screenshots**
Screen Shot 2020-05-07 at 11 20 35 AM

### PR DESCRIPTION
**Pull request by TrevorBivi**
Changes the title text on other people's profile

profile vs myprofile title

### CODE REVIEW

**Review by dynamic11 — APPROVED** [review]
looks good!

**Review by BenJeau — CHANGES_REQUESTED** [review]
Could you also update the french i18n file, it would be `Profil`, aside from that, it looks good!
image

**Comment by dynamic11** [comment]
good catch @BenJeau

**Comment by dynamic11** [comment]
is this ready for merge?

**Comment by TrevorBivi** [comment]
Whoops yes. I just figured out how re-requesting review works. I have made the requested change

**Review by BenJeau — APPROVED** [review]

**Pull request merged**
