### PR TITLE
[Fix] Backend core profile fix

### PR DESCRIPTION
**Pull request by mo-5**
- Updated how private and public profiles are handled. 
- Fixed the update method for profile.

### CODE REVIEW

**Review by BenJeau — COMMENTED** [review]
Seems to work, but I think the information is returning is not the correct one

ex: skills
image
should probably only be containing 
```json
{
  "id": "",
  "name": ""
}
```
and same thing with competencies, developmentalGoals and for many of the different fields.

I think we should not send the updatedAt/createdAt to the client and also if the id is not relevant, like the one in visibleCards (if we want to update that info, it should just fetch the one of the user and update that visibleCard)

**Comment by BenJeau** [comment]
And we should only send back the info in one of the language 

ex:
image

to become?
```json
{
  "tenure": "Term",
  "careerMobility": "Develop in role",
  "jobTitle": "Manager",
  "branch": "Human Resource Branch",
}
```

**Comment by BenJeau** [comment]
Looks way better than before, but just one comment, I made a query to `/api/profile/:id`
image
I think for these values, since its not a list, I would just return something like 
```json
{
    "groupLevel": "CS 05",
    "actingLevel": null,
    "securityClearance": "Top Secret",
    "lookingJob": "Not looking",
    "tenure": "Term",
    "careerMobility":  "Develop in role",
    "jobTitle": "Manager",
    "branch": "Human Resources Branch",
    "talentMatrixResult":  "Early promise"
}
```
what do you think?

**Comment by BenJeau** [comment]
Also I don't see you returning info about the second language proficiencies, in the past we were returning the info like this 
image
but I think it would either just be this
```js
secondLanguageProficiencies: {
  oral: {
     level: 'A',
     date: '',
  },
  writing: {
     level: 'A',
     date: '',
  },
  reading: {
     level: 'A',
     date: '',
  },
}
```
or like this since its stored as an array in the db

```js
secondLanguageProficiencies: [
  {
     proficiency: "oral",
     level: 'A',
     date: '',
  },
  {
     proficiency: "writing",
     level: 'A',
     date: '',
  },
  {
     proficiency: "reading",
     level: 'A',
     date: '',
  },
]
```

**Comment by mo-5** [comment]
Fixed in the new commit. I also added ID check to make sure the user matches for the private profile. I also fixed the frontend for creating user in the database.

**Review by BenJeau — APPROVED** [review]

**Pull request merged**
