### PR TITLE
[Fix] migrate to apex charts

### LINKED ISSUE #950: Move from Bizcharts to Chartjs-2
**Is your feature request related to a problem? Please describe.**
Bizcharts documentation is all in Mandarin and may the charts part of our code may not be well understood by maintainers later on... I just saw that the covid19 Ontario website is using ant design for the table and ApexCharts for its charts. At least their docs are in english and the design is not that bad

**Describe the solution you'd like**
We should probably move to ApexCharts https://github.com/apexcharts/react-apexcharts

**Additional context**
You can see which library they use by looking at the source code of the website

https://covid-19.ontario.ca/data

### PR DESCRIPTION
**Pull request by mo-5**
#### Changes introduced

The style is a little different. I can't find much customization for apex charts. However, the application is much lighter. 
#### Related issue(s)

closes #950
#### Screenshots (if applicable)

image

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by mo-5** [comment]
also, @BenJeau when I try to create the analyze graph this is the error I get 
image

**Comment by mo-5** [comment]
I think it does make a big difference because bizchart seems to have a lot of peer dependencies

**Comment by BenJeau** [comment]
For the analyze, you need to attach your shell to the frontend contianert

**Comment by mo-5** [comment]
oh, I didn't realize that loool. Sounds good, thanks. 
image
I am not sure if it made any difference tbh. It seems like apex chart import is pretty large

**Comment by BenJeau** [comment]
What lol, that's weird... I'll pull your branch and play with it a bit. But yeah, it does seem really big

**Comment by mo-5** [comment]
Will Convert to chart.js since it's smaller.

**Pull request closed without merging**
