### PR TITLE
[Fix] Results header not shown when page accessed through URL

### LINKED ISSUE #1064: Show results header when accessing /results
**Is your feature request related to a problem? Please describe.**
When accessing the results page from the url, theres a header missing

What is happening now:
image

**Describe the solution you'd like**
Add a header to that page that says results 0, but that keeps the current message

image

### PR DESCRIPTION
**Pull request by SukhsimranpreetSekhon**
#### Changes introduced

- Fixes issue where results page, when accessed through direct URL (/results), did not display the correct icon ("Results") and search matches ("Found: ") for the header.

#### Related issue(s)

closes #1064 

#### Screenshots (if applicable)

image

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [x] The modifications are tab friendly
- [x] It is accessible

### CODE REVIEW

**Review by BenJeau — COMMENTED** [review]
Like the change, if you remove the usage of the image, could you also delete the image "./online_team_meeting_.svg"?

**Comment by SukhsimranpreetSekhon** [comment]
> Like the change, if you remove the usage of the image, could you also delete the image "./online_team_meeting_.svg"?

Hey, Docker is working now for me. I was able to use the image when someone would directly access the page through the URL.

**Comment by dynamic11** [comment]
this PR has a linting issue that needs to be addressed

**Comment by SukhsimranpreetSekhon** [comment]
> this PR has a linting issue that needs to be addressed

Fixed. Restarted the checks for branch and PR. Fixed issues instantly.

**Review by dynamic11 — APPROVED** [review]

**Pull request merged**
