### PR TITLE
[Feat] Add visibility toggle in forms

### LINKED ISSUE #495: Add privacy buttons to every card on Edit Profile Page
**Is your feature request related to a problem? Please describe.**
When a user first creates their profile, there's no indication on whether the information they are entering will be kept private or public, unless they go through the privacy statements or FAQs beforehand. 

**Describe the solution you'd like**
We should add the privacy buttons on the Edit profile page so that new users can set up their privacy settings as they create their profile.  This way, they can edit their privacy settings from the Edit page as well. 

**Additional context**
image

image

### LINKED ISSUE #570: In the profile, when you hover over the pencil it says "private" instead of edit
**Describe the bug**

In the profile, when you hover over the pencil it says "private" 

**Expected behavior**
It should say, "edit" everywhere the pencil is used 
 
**Screenshots**
image

**Additional context**

### LINKED ISSUE #571: Change mouse over wording for privacy buttons
**Is your feature request related to a problem? Please describe.**
The privacy buttons should be a little more discriptive to help people really understand what they mean in terms of visility of the data to others on the platform. 

**Describe the solution you'd like**
I recommend we make the followings changes:

From: private,  To: Card only visible to you
From: public, To: Card visible to everyone
From: connections, To: Card visible to connections only

image

image

image

### PR DESCRIPTION
**Pull request by BenJeau**
#### Changes
- Extracted the visibility toggle component
- Added the toggle to every section for the forms (closes #495)
- Changes the hover for the edit pen button to "Edit" (fixes #570)
- Fixes hover of visibility toggles (fixes #571)
> Note: the OL toggle depends on its profile card being seperated (so it will seem like it won't work right now, but it is updating the correct value in **visibleCards**), until the PR from Trevor to seperate the card is created/merged
#### Screenshots
image
image
image
image
image

### CODE REVIEW

**Comment by TrevorBivi** [comment]
I noticed that some times when you change the visibility setting of a card and refresh the page it isn't saved. Trying to see if there's an obvious reason I'm seeing this.

**Comment by BenJeau** [comment]
@TrevorBivi In this branch specifically or in dev? Regardless it should be fixed (probably in this PR), just wanted to know if I introduced it

**Comment by TrevorBivi** [comment]
@BenJeau It seem to only be seeing it on this branch and not dev.

**Comment by TrevorBivi** [comment]
I figured out how to reproduce it. It seems that if you make multiple changes and then refresh only the last change is applied. Looking at the put requests being sent, the values being sent for visibility values only seem to show the change for the last card. The others are set back to the original value. This happens both on forms and when editing visibility straight on the profile.

**Comment by BenJeau** [comment]
Oh that makes sense, I have an idea on how to fix it. Thanks for finding that!

**Comment by BenJeau** [comment]
Now works as expected (but is modifying the params, which is not great, its currently done like that on dev), once we move to something like redux-thunk, this should be fixed, #448. @TrevorBivi can you retry to see if it works?

**Comment by TrevorBivi** [comment]
It's working perfectly for me now

**Review by TrevorBivi — APPROVED** [review]

**Pull request merged**
