### PR TITLE
[Fix] Added missing translation in Education form and experience forms

### LINKED ISSUE #1195: translation for description missing in education and experience forms
**Describe the bug**
translation for description missing in education and experience forms

**To Reproduce**
1. Go to create profile
2. Click on qualifications form
3. Scroll down to 'description field''

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Mousto097**
#### Changes introduced

- Added missing translation for description in education and experience forms
- Fixed padding issue in education form

#### Related issue(s)

closes #1195 

##### before
image

##### after
Screen Shot 2020-12-30 at 12 34 06 PM

### CODE REVIEW

**Review by dynamic11 — APPROVED** [review]

**Comment by dynamic11** [comment]
i also found this
image

**Comment by dynamic11** [comment]
also this. it shows up in the console aswell on the profile page.
image

**Comment by dynamic11** [comment]
also checkout the console log in the admin dash

**Comment by dynamic11** [comment]
image

**Comment by mo-5** [comment]
there is also this 
image

**Pull request merged**
