### PR TITLE
[Fix] Jenkins loadsh

### LINKED ISSUE #999: i18n:check fail due to lodash-es
**Describe the bug**
please see attached screenshot. i see this error when I go to run the check. this blocks jenkins tests aswell

**To Reproduce**

**Expected behavior**

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by mo-5**
#### Related issue(s)

closes #999

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by BenJeau** [comment]
Looks good, but it is still failing since in the check and cleanup files, you can't use `import ...`, you need to use `const ...` like in the backend to import packages

**Comment by mo-5** [comment]
I have a question about this. Do you know if this gets added to the build package? like the module files? Since if not we could just go back to lodash regular import @BenJeau Do you know?

**Comment by BenJeau** [comment]
Mhhh not 100% sure. But I know as a matter of fact, you know how you seperated each lodash function with a different import, that wouldn't make a difference here. Also, with the babel-plugin-import that is being used for ant design and validator.js, it can be used for lodash-es and we could just have it so we import normally and let babel take care of splitting it in different imports. I'm just having trouble getting multiple instance of that plugin to work, but according to babel and the issues/readme of the plugin, it should be feasible.

**Comment by mo-5** [comment]
I see because we cant use lodash-es for the i18 checks. I will modify that to regular lodash.

**Comment by BenJeau** [comment]
Ohhh, is it because for lodash-es, you need to import it with import because that is the es format?

**Comment by mo-5** [comment]
Yeah

**Review by BenJeau — APPROVED** [review]
The only issue I see with this is that we won't be able to run it locally, since lodash is not specified in our package.json - I'll accept it since Jenkins is more important than running it locally. I think there's a linter issue now - you can fix it in this branch if you want

image

**Comment by mo-5** [comment]
Yeah, I was thinking about the local thing. I am not sure what's the best way to approach this. I was thinking of just creating a separate package.json file for it.

**Comment by BenJeau** [comment]
I think you could add lodash to the package.json and it would work? I don't it would add it to the react-bundle, as weird as it sounds - but you can for sure just add another package.json (maybe one at the root of the repo?)

**Pull request merged**
