### PR TITLE
[Fix] Update backend packages and replace the keycloak mock 

### PR DESCRIPTION
**Pull request by mo-5**
#### ⭐ Changes introduced

- Update backend packages.
- Moved keycloak mock to cdh studio and updated the packages for that.

#### ☑️ Checklist

If the database has been modified:

- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:

- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak

If the UI has been modified:

- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:

- [ ] run `yarn i18n:validate" and clear errors

### CODE REVIEW

**Comment by dynamic11** [comment]
should we merge this or wait till after demo?

**Comment by mo-5** [comment]
> should we merge this or wait till after demo?

it should effect the demo but we should probably wait for after just incase

**Comment by mo-5** [comment]
@dynamic11 Is this good to merge ?

**Review by dynamic11 — APPROVED** [review]
tested and no issues for me 💯

**Pull request merged**
