### PR TITLE
[New] Migrate to scss

### LINKED ISSUE #861: Migrate to scss
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by mo-5**
#### Changes introduced
- Migrate to scss from in component styling.
- Removed some controller logic from view. 

#### Related issue(s)
closes #861

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by BenJeau** [comment]
Looking over the PR, looks great, but while testing it locally saw a few differences, I'll just post screenshots here. Please let me know if some of those changes are made on purpose. There may be more differences, those are just the ones that stood out for me

-----------

### Create flow
#### Sidebar
This PR (more spaced and has bullets):
image


Before:
image


### Profile page
#### Header (same thing for header of edit/admin/settings)
This PR: 
image

Before:
image

#### Sidebar
This PR (has less padding):
image

Before:
image


### Search page
#### Results card
This PR (notice the line/divider that doesn't expend the height of the container and the space under the name of the person):
image

Before:
image

### Navbar
#### Dropdown menu
This PR:
image

Before:
image

### Footer
This PR (has no background color):
image

Before:
image

**Comment by mo-5** [comment]
- I made the modifications to the Nav Dropdown menu - I thought it looks nicer being more compacted instead of the paddings we had. But I can definitely change that back. 
- For the Side nav bar I have also made the changes to bullet points not sure if that looks nicer than the "-". I could also move that back. 

- I will take a look at the footer and the second sidebar. Since the search has been redesigned by Ali I will just take his changes.

**Comment by BenJeau** [comment]
I think for the menu dropdown, making it a bit more spaced is good. And for the bullets, if you are making the change, I think we would need to also make it in the edit profile pages. @dynamic11 what are your thoughts?

**Comment by dynamic11** [comment]
I agree with benoit about the dropdown. However, I do like the sidebar menu without '-'. The only concern I have is when the sidebar option breaks into two lines. how will the user differentiate between a new item and just a title with a line break? If we can resolve that concern I'm good with removing the '-'

**Comment by mo-5** [comment]
Should be good now please take another look.

**Review by BenJeau — COMMENTED** [review]
Sorry for the late re-review, some small comments (just comparasion to what we have right now). @dynamic11 feel free to review this PR once its done, if ever I forget it, like I just did

1. The navbar seems to be a different color than before?
image
2. There seems to be missing some padding in the tabs in the about/help..
image
3. The visibility toggles seems to be missing some bottom padding
image
4. Employment status, official languages, skills and comp forms seems to have too much bottom padding or something compared to the other forms in the header
Peek 2020-09-29 10-15
5. The header of the section under the tab in qualifications and career and talent management seems big
image
6. All the headers seems to have too much padding - admin/edit/profile
image
image
7. The org section in the profile does seem to align properly
image
Compared to
image

**Comment by mo-5** [comment]
Oh yeah, you are right I didn't notice these I will fix them. Thank you

**Comment by BenJeau** [comment]
Could we try to get this merge, so we get less conflict in the future

**Comment by mo-5** [comment]
I am looking into the database migration so it will be hard to get this done today. You can merge your changes and I will take care of the conflicts.

**Comment by BenJeau** [comment]
I'll take over this PR to not have weird conflicts with the other PR

**Review by dynamic11 — APPROVED** [review]
LGTM

**Review by BenJeau — APPROVED** [review]

**Pull request merged**
