### PR TITLE
[Feat] Add description to edit profile sidebar

### LINKED ISSUE #128: See if profile forms have unsaved changes
- add a small status for the profile forms to see if there are unsaved changes

### LINKED ISSUE #130: add details for each menu item in sidebar of edit profile
- like profile setup steps add details to each form link in side bar
- this will help the user navigate to the correct section easier

### PR DESCRIPTION
**Pull request by BenJeau**
Added description to side bar menu like in create profile

closes #130 

### Before
image

### After
image

### CODE REVIEW

**Comment by BenJeau** [comment]
Based on feedback, this is the updated look
image

**Review by dynamic11 — APPROVED** [review]
Looks good!

**Comment by MenaMachado** [comment]
Hi Ben,  Can you make the following editorial changes in Edit Profile side bar. 

Primary information to "Contact information" (Coordonnées) *
Talent to "Competencies and skills"
Personal Growth Interest to "Career & talent management" (gestion de la carrière et des talents)*
Career Interests to "Job mobility" (mobilité de l'emploi)*

**Also,** only the first letter in any heading should be in capital, the rest is in lower case. 

And make the same changes to the "My Profile" page for the three items I marked with a star above.

**Comment by BenJeau** [comment]
Yes, I'll make those changes 🙂

**Pull request merged**
