### PR TITLE
[Update] nodejs in docker

### PR DESCRIPTION
**Pull request by mo-5**
#### Changes introduced

update to 12.19.0 please test locally to make sure it works. 

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by mo-5** [comment]
Also, I just noticed if we moved to npm for our node js image will shrink by ~half 

https://github.com/mhart/alpine-node

**Comment by BenJeau** [comment]
But it seems like we would need to revert to an older version of node.js? I think it would be v6?

**Comment by mo-5** [comment]
I don't think these are referring to the versions of the node. 0.10.48 would be a pretty old version. I think it's an internal versioning.

**Comment by BenJeau** [comment]
But I think it is, looking up online they are valid node.js versions, the latest v0.12 release was in 2016 and v4 was in 2018 (and looking inside of the Dockerfiles they are using, it is specifying that node version). Its weird that they have it there

**Review by BenJeau — APPROVED** [review]
Works for me locally

**Pull request merged**
