### PR TITLE
[Feat] Updated frontend packages

### PR DESCRIPTION
**Pull request by BenJeau**
#### Changes introduced

- Updated deps with `npx npm-check-updated -u`
- Had to keep the version of `eslint` to `6.6.0` due to `craco`
- Because of the breaking change of `@react-keycloak/web`, had to update the code a bit

 @react-keycloak/web      2.1.4  →    3.0.0   
 antd                     4.6.4  →    4.7.0   
 dayjs                   1.8.35  →    1.9.3   
 query-string            6.13.2  →   6.13.5   
 react-intl               5.8.1  →    5.8.6   
 validator               13.1.1  →  13.1.17   
 eslint-config-prettier  6.11.0  →   6.12.0   
 eslint-plugin-import    2.22.0  →   2.22.1   
 eslint-plugin-react     7.20.6  →   7.21.4

### CODE REVIEW

**Review by dynamic11 — APPROVED** [review]
tested! looks good!

**Comment by mo-5** [comment]
Jenkins is actually failing because of linting issues. not sure if they are introduced by this pr

**Comment by BenJeau** [comment]
Mhh its weird. Just linted development, and it shows the same warnings/errors

**Comment by dynamic11** [comment]
I believe the update to DayJS is causing front end to crash (Related to #962)

**Pull request merged**
