### PR TITLE
[Fix] Consistent I-Talent/frontend naming convention (renamed anything related to upskill)

### PR DESCRIPTION
**Pull request by BenJeau**
#### Changes introduced

- Renamed `services/frontend-v3` to `services/frontend`
- Named docker-compose network
- Named docker images built inside docker-compose
- Removed `webpackbar` (was useful to know at what % the build was at, but ruined the logs)
- Renamed anything `upskill` to `italent`
- Renamed `web-ant` to `frontend`

> Note: this may seem like a big PR, it is just because this renames the frontend services folder, which inherently renamed the files inside of it

#### Related issue(s)

https://github.com/CDH-Studio/I-Talent/pull/988#issuecomment-715582740

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by mo-5** [comment]
I love this change but the only issue I would see is that all the pr will have merge conflicts because of the directory name ? or how will that work. 

Maybe we should leave the directory as v3 for now?

**Comment by BenJeau** [comment]
I was also wondering if it would cause conflicts
 Let me try merging one of the open PRs branch with this one to see what happens. If it doesn't go well, I'll revert the folder name change

**Comment by BenJeau** [comment]
I was able to merge successfully the `make-visibility-toggle-accessible` branch (#987)
image

Same with `search-bar-associated-label` branch (#946)
image

But `feat-remove-signin` branch (#994) causes a conflict
image

same with the `create-profile-qualified-pools-card` branch 
image

@MohamedRadwan what do you think about this? I think we should merge it with the folder name change, but I want your input. If people are having trouble merging them, I can help them with it - I would say it in the chat. The merge conflicts don't seem that bad.

**Review by mo-5 — APPROVED** [review]

**Comment by mo-5** [comment]
Yeah I agree I think we should just merge it

**Pull request merged**
