### PR TITLE
[Fix] Fixed profile view

### PR DESCRIPTION
**Pull request by BenJeau**
Reduced the number of calls the profile view makes to the backend
Fixed the API calls made to the backend (including how the data is formatted)
Make skills and mentorshipSkills return the categoryId and category name in the profile response

### CODE REVIEW

**Comment by mo-5** [comment]
I am getting this error on admin users page. I think this is caused becuase we removed the get all users method. 

image

**Comment by mo-5** [comment]
I get this error when I try to visit mary doe or john does profile 
image

Looks like the issue is the api call is not made with the language
image

**Comment by BenJeau** [comment]
The bugs you encountered should be fixed now

**Review by mo-5 — APPROVED** [review]
Looks good !

**Pull request merged**
