### PR TITLE
[New] Update school list

### LINKED ISSUE #744: Update list of schools
**Is your feature request related to a problem? Please describe.**
The list of schools needs to be updated. Casey will provide the list in excel to update UAT, Dev and for Prod

### PR DESCRIPTION
**Pull request by mo-5**
#### Changes introduced
Update the school list with the list provided by Mena. This will delete all user's eductions.

#### Related issue(s)
closes #744

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Review by BenJeau — COMMENTED** [review]
looks good, but I see a lot of ids in the dropdown - 
image

I even dropped my db and restarted docker

**Comment by mo-5** [comment]
that's weird it worked on my side. Let me try it again.

**Comment by mo-5** [comment]
Should be fixed now. Please retest it, thank you.

**Review by BenJeau — APPROVED** [review]
Looks good, just seems to be missing a few colleges that are in ottawa, like Collège La Cité and Algonquin College - but this is not because of you, so I'll accept it

**Comment by mo-5** [comment]
I copied the list but it shouldn't be missing Algonquin. I will double check this.

**Comment by mo-5** [comment]
Yeah, it doesn't seem to be on the list. @MenaMachado I was wondering if Algonquin is not on the list intentionally?

**Comment by MenaMachado** [comment]
I'll look into the missing colleges.

**Comment by MenaMachado** [comment]
All the colleges in Canada are missing  in the list.  Casey is working on it.

**Comment by MenaMachado** [comment]
good catch guys!

**Comment by mo-5** [comment]
> All the colleges in Canada are missing in the list. Casey is working on it.

Sounds good. If you could just open a ticket with only the missing colleges so that I could create a pull request for them.

**Pull request merged**
