### PR TITLE
[New] Added field for changing job title in profile forms

### LINKED ISSUE #524: Add position title field to Profile
**Is your feature request related to a problem? Please describe.**

Users can manually add their job title to their profile

**Describe the solution you'd like**

- On the Edit profile page in Contact information card, add a field under the first name to manually add their position title.
- In the user profile the title should be displayed just below the user's name

image

image

### LINKED ISSUE #788: Org chart not showing on profile
**Describe the bug**
Org chart not showing on profile. Issue is only on development. UAT is working which means it broke from August 8th onwards.

image

### PR DESCRIPTION
**Pull request by KateAThornley**
#### Changes introduced
This change adds a new field to the profile's edit and creation (primary info) forms. The field is titled 'Job title' and allows the user to change the information in the field synced with GEDS or enter in their own custom title from the start. When the user wants to change the title in their second language they simply change the app's language and enter in their second custom title.

#### Related issue(s)
fixes #524 

#### (screenshot of notification upon save coming)
image

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [x] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [x] The modifications are tab friendly
- [x] It is accessible

### CODE REVIEW

**Review by BenJeau — COMMENTED** [review]
I may be missing something, but weren't you supposed to add the modal when a user modified that particular field?

**Review by BenJeau — APPROVED** [review]

**Review by BenJeau — CHANGES_REQUESTED** [review]
^

**Comment by BenJeau** [comment]
If I remember, this PR introduces new bugs with the job title (regarding updating the job title, it sometimes won't do it - I have an idea why), but @dynamic11 do we want to merge this and for me to open a new issue and open a new PR fixing those bugs? I know this also fixes #788

**Comment by dynamic11** [comment]
> If I remember, this PR introduces new bugs with the job title (regarding updating the job title, it sometimes won't do it - I have an idea why), but @dynamic11 do we want to merge this and for me to open a new issue and open a new PR fixing those bugs? I know this also fixes #788

to be honest with you thats up to you. If you think the fix is fast then go ahead. OR just work off of this branch

**Review by BenJeau — APPROVED** [review]
Will open a new issue to address the edge cases of this PR

**Pull request merged**
