### PR TITLE
[Fix] Make fields in admin page tables required on edit 

### LINKED ISSUE #1575: Can make blank entry in Admin
**Describe the bug**

When editing an entry in the admin pages, it is possible to delete the labels and leave the entry blank

**To Reproduce**

1. Go to Admin page
2. Select a table
3. Edit an entry
4. Delete the fields
5. Save

**Expected behavior**

The fields should be required

### PR DESCRIPTION
**Pull request by mo-5**
#### ⭐ Changes introduced

This will prevent the user from adding white space into the table. 

#### 🔗 Related issue(s)

closes #1575 

#### ☑️ Checklist

If the database has been modified:

- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:

- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak

If the UI has been modified:

- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:

- [ ] run `yarn i18n:validate" and clear errors

### CODE REVIEW

**Review by dynamic11 — APPROVED** [review]

**Comment by dynamic11** [comment]
can we add a back a backend validation for this as well?

**Review by Rizvida1 — APPROVED** [review]

**Review by dynamic11 — CHANGES_REQUESTED** [review]
please add backend validation 🙏

**Comment by mo-5** [comment]
> please add backend validation 🙏

Done

**Comment by dynamic11** [comment]
will review shortly :)

**Review by dynamic11 — APPROVED** [review]
🚀

**Pull request merged**
