### PR TITLE
[Fix] Clean up duplicate values in json files (Fr/En)

### LINKED ISSUE #1096: Add script to find duplicate values in json files (Fr/En) and Clean up all duplicates
**Describe the bug**
In order to avoid duplicates in the json files we need to add a script that will find all duplicate values in en_CA.json and fr_CA.json files.

**Screenshots**

***en_CA.json***
Screen Shot 2020-11-23 at 7 55 03 PM

***fr_CA.json***
Screen Shot 2020-11-23 at 7 55 20 PM

**Additional context**
Script to find duplicates can be added in `frontend/src/i18n/check.js`

### PR DESCRIPTION
**Pull request by Mousto097**
#### Changes introduced

- Added script to find duplicate values in json file (Fr/En) --> Script is located in: `frontend/src/i18n/check.js`
- Cleaned duplicate values in json files

#### Related issue(s)

Closes #1096 

#### Checklist
If the UI has been modified:
- [x] It is translated in both language (with no hard coded text)

### CODE REVIEW

**Comment by Mousto097** [comment]
@dynamic11 @BenJeau  
Before you guys review this PR, there is something you need to know. We have a lot of duplicates because of our naming convention. For instance:

- `"profile.education": "Education"`
- `"setup.education": "Education"`

Should change our naming convention in order to avoid this situation?

**Comment by BenJeau** [comment]
I think that sounds good, the only issue that I see with this overall PR is the following edge case (I'm not sure if it takes care of it or if you have thought of it)

- What happens if there's a value that is a duplicate in the English translation file, but in French, those two keys refer to different values? I'm not sure if this is something that is happening in our codebase, but sounds like it if there's a different number of "duplicate values" from French and English. Or did you just rename things so that this problem is non-existant?

**Comment by Mousto097** [comment]
@BenJeau  You're right!

Whenever there's a value that is a duplicate in the English translation file, but in French, those two keys refer to different values, I either just rename things to solve the problem or leave as is. A good example for this case is:

- ` "admin.search.button": "Search"` <==> `"admin.search.button": "Chercher"`
- `"bugs.location.search": "Search"` <==>   `"bugs.location.search": "Recherche"`
- `"button.search": "Search"` <==> `"button.search": "Rechercher"`
- `"setup.select": "Search"` <==> `"setup.select": "Rechercher"`

**Became**

- `"search": "Search"` <==> `"search": "Rechercher",`
- `"input.placeholder.select": "Search"` <==> `"input.placeholder.select": "Rechercher",`

What do you think?

**Comment by dynamic11** [comment]
can we prepare this for merge? I can review this on monday once the branch has been update with dev 💯

**Comment by Mousto097** [comment]
@dynamic11 its ready for review ✅

**Review by dynamic11 — APPROVED** [review]

**Pull request merged**
