### PR TITLE
Handle get request errors

### LINKED ISSUE #171: Handling promises error properly when making queries to backend
**Describe the bug**
If a call is made to the backend, we are assuming (at someplace, maybe everywhere) that it will return data and not necessarily raise an error. 

One of my chrome extension blocked a call since it thought it was a tracker or something. The app was trying to make a call to https://sso-dev.ised-isde.canada.ca/auth/realms/individual/protocol/openid-connect/token and the promise return an error, which then doesn't load any page except / (which doesn't need authentication).

**To Reproduce**
Install the EEF Privacy Badger extension and login to the app. Once logged in, the error will be raised

**Expected behavior**
We should handle these errors and show related something to the user instead of a blank page.

**Screenshots**
image

**Additional context**
Probably related to not having a catch for the keycloak promise call

### PR DESCRIPTION
**Pull request by TrevorBivi**
Handles get request errors encountered by rendering error components instead of the content dependent on the get request.

closes #171 

Notes:
- The error components are almost identical. I could change the code so that all areas render the same error component instead, I thought it might be better to separate them so they can be stylized more differently in the future.

Images of all the different error components in action:
AdvancedOptions
EditProfileError
filterOptionsError
profileCardErrors
profileError
ResultsError
welcomeError
AdminError

### CODE REVIEW

**Comment by dynamic11** [comment]
We should have a 3 way call to discuss some modifications between @dynamic11, @TrevorBivi and @BenJeau

**Comment by dynamic11** [comment]
@TrevorBivi can you contact me on teams? i cant message you for some reason

**Comment by TrevorBivi** [comment]
> We should have a 3 way call to discuss some modifications between @dynamic11, @TrevorBivi and @BenJeau

Sure, I am unable to join the Dev chat for some reason. I think something upset MS Teams after the third account of mine had to be added?

**Comment by TrevorBivi** [comment]
> @TrevorBivi can you contact me on teams? i cant message you for some reason

I sent a direct message hopefully it goes through

**Comment by dynamic11** [comment]
> > @TrevorBivi can you contact me on teams? i cant message you for some reason
> 
> I sent a direct message hopefully it goes through

can you just switch to the guest account for now? it doesnt seem to be working.

**Comment by dynamic11** [comment]
To be less intimidating I was thinking we do something like this.
image

**Comment by dynamic11** [comment]
It was decided as a group that we will implement:
- an error handling function that will take in the errors
- redirect to a friendly error page (like our 404) and prompt the user to try to reload
- user can expand to view errors on error page

**Review by dynamic11 — CHANGES_REQUESTED** [review]
this PR will wait for modifications

**Pull request closed without merging**
