### PR TITLE
[New] Added keyboard and screen-reader accessibility across app

### LINKED ISSUE #235: Ensure Keyboard Accessibility
**Is your feature request related to a problem? Please describe.**
Ensuring that our application is completely accessible is a necessity for product release and UAT. For users that have mobility issues we need ot mkae sure the site is fully functional via keyboard navigation.

**Describe the solution you'd like**
ensure all components can be tabbed to and add functions to detect onKeyPress for enter when lacking

**Additional context**
Contact Colleen Hickey for information/guidence

### LINKED ISSUE #310: Ensure Screen-reader on all pages works (accessibility)
**Is your feature request related to a problem? Please describe.**
Accessibility is a necessitity for our application so for those with visual imparments we need to make sure screen readers can read our site properly and in an order that makes sense to the user.

**Describe the solution you'd like**
Ensure all <title> tags are descriptive
Headings should follow a hierarchy
Add alt text to all images/icons
Test with a screen reader

### PR DESCRIPTION
**Pull request by KateAThornley**
- Added global styles for all :focus elements across app 
- Added tabbing to home page/search, results page, profile and profile setup/edit pages
- Added alt text
- Added new tabbing functions to detect when pressing enter to trigger component
- Ensured WAV Accessibility extension passed on all pages
- Ensured header hiearchy across app for screen reader
- Added hidden h1 titles across app for reader

### CODE REVIEW

**Comment by TrevorBivi** [comment]
It seems like you can toggle advanced options with just keyboard, but I don't think it does anything to display that you have the advanced options button selected

**Comment by TrevorBivi** [comment]
On the qualifications form it does not seem possible to uncheck ongoing and I don't see any visual change when the delete button is selected

**Comment by TrevorBivi** [comment]
The toggle button to expand the description on the experience card does not visually change when selected

**Review by BenJeau — APPROVED** [review]
Works locally :100: , the only comment I have is to try to not push commented code

**Pull request merged**
