### PR TITLE
[New] frontend package update 2021/05/12

### LINKED ISSUE #1375: update chart js to 3.x
**Is your feature request related to a problem? Please describe.**
A large breaking update was made to chart js. we should adopt it

### PR DESCRIPTION
**Pull request by dynamic11**
⭐ **Changes introduced**
Updated frontend node packages
❗ ❗ This is a big change, Please test thoroughly❗ ❗

ℹ️  **Related issue(s)**
Closes #1375 

📸  **Screenshots (if applicable)**
no screenshots

### CODE REVIEW

**Comment by dynamic11** [comment]
The site now fails to load in IE

**Comment by mo-5** [comment]
I am getting these errors when I try to build it. I think it has to do with merging development into this branch I will look into it.

image

**Comment by dynamic11** [comment]
@mo-5 This is caused due to linting rules changing since the upgrade. Run yarn lint -fix and see if it resolves it

**Review by mo-5 — APPROVED** [review]
LGTM

**Review by Rizvida1 — APPROVED** [review]
Seems to be working fine

**Comment by dynamic11** [comment]
too many conflicts so #1408 was made instead of this

**Pull request closed without merging**
