### PR TITLE
[Fix] Update deps - Minimize react-bundle

### PR DESCRIPTION
**Pull request by BenJeau**
#### Changes introduced

- Added babelrc file, which allows for multiple instance of the `babel-plugin-import` (to shrink the react-bundle and not having to do the tree shaking manually in the code)
  - Removed manual tree shaking for lodash and validator.js
- Added `webpack` and `babel` plugins to reduce lodash size
- Added `webpack` ignore plugin to ignore the moment.js locales (doesn't seem to affect the application)
- Explicitly set browserlist in `.neutrinorc.js`, remove arrow functions from JS uglifier, explicitly set IE compatibility in babel plugins (but doesn't seem to still work on IE...)
- Updated frontend deps

I updated the deps in hopes to fix IE

> **Note:** I didn't update React to v17 since ant design is not supporting it right now, according to one of the issues, they will support it in the next major release, aka v5 (but neutrino supports it)

#### Screenshots (if applicable)

Before:
Screenshot from 2020-11-04 09-59-52
Screenshot from 2020-11-04 09-59-52

This PR:
Screenshot from 2020-11-04 09-57-53
Screenshot from 2020-11-04 09-57-53

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by BenJeau** [comment]
**Note:** the lodash fix is actually breaking the application... I need to look into it more

**Comment by mo-5** [comment]
Are the issues in IE related to antd ?

**Comment by BenJeau** [comment]
I don't think so, I think its related to neutrino.js, forgot to link the issue #1017 - I will jump back on this PR today, and plan on making it ready for review

**Comment by BenJeau** [comment]
@MohamedRadwan Please test this branch locally (remove docker images/container and build from scratch) to make sure that it is not breaking anything major. It was breaking for me in the past, but just tried it today and it seems fine, not sure what changed

**Comment by BenJeau** [comment]
Potential fix for #1055 (may be related to the update to axios)

**Comment by mo-5** [comment]
I will test it out and see do you think we should add obfuscation for the javascript as part of this PR. I am not sure if that is just a one line code in the webpack configuration or not but it might be helpful to keep the frontend code secure.

**Comment by BenJeau** [comment]
There seems to be a webpack plugin, https://github.com/javascript-obfuscator/webpack-obfuscator, but I'm not sure if we need obfuscation since technically our code is open source and it is only used internally

**Comment by mo-5** [comment]
Yeah that is true

**Comment by dynamic11** [comment]
I just tested this PR and seems to be working but IE is still not loading. I believe the PR title should be changed since IE still not fixed.

**Review by dynamic11 — APPROVED** [review]

**Pull request merged**
