### PR TITLE
[New] Introduce tabs to edit

### LINKED ISSUE #686: Break the Qualifications page
Break the qualifications page into 2 section:

Eduction:
image
Experince:
image

### LINKED ISSUE #705: Add tabs to subcategories in create/edit profile
Add tabs to reduce the page size.

### PR DESCRIPTION
**Pull request by mo-5**
image
image
image

closes #686 
closes #705

### CODE REVIEW

**Comment by BenJeau** [comment]
Seems to be one small visual bug, there seems to be not padding horizontally here
image

**Comment by mo-5** [comment]
image


I have updated the style however I found another bug that is present in the dev branch. I opened a ticket for it #708 and will take a look into it.

**Comment by BenJeau** [comment]
Sounds good, I think I know why that bug exists, also can you remove the three i bubbles? feels like a lot in a small section, maybe only keep one? what do you think

**Comment by mo-5** [comment]
I agree I have made the following changes: I have added all of them in case you want to check them out

image
image
image
image
image
image
image
image
image

**Comment by BenJeau** [comment]
For mentorship skills, can you keep the switch next to the title (so its consitstent in the other forms) and can you remove the second i? Aside from that it looks good!

**Comment by mo-5** [comment]
I see your point. I have made the modification. 

image

**Comment by BenJeau** [comment]
I feel like I keep coming with modifications (ahh), but can you make it so there more space between the toggle and the input field? it feels squished

**Comment by mo-5** [comment]
Done 
image

**Review by BenJeau — APPROVED** [review]

**Pull request merged**
