### PR TITLE
[Fix] Reduce package size

### PR DESCRIPTION
**Pull request by mo-5**
#### Changes introduced

- Moved from lodash to lodash-es (smaller bundle)

#### Related issue(s)

related to #975

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by mo-5** [comment]
Could you guys please let me know if there is a way to create that graph to show each component size? I wasn't able to get it.

**Comment by BenJeau** [comment]
Yes, you can find the steps here https://github.com/CDH-Studio/I-Talent/tree/development/services/frontend-v3#yarn-analyze, hope it still works

**Comment by BenJeau** [comment]
run `yarn analyze` not `run analyze`, there's a type in the readme. It creates a production build and analyzes it

**Comment by mo-5** [comment]
Yeah it just shows the total build size and not that graph we had before

**Comment by BenJeau** [comment]
Let me try locally

**Comment by BenJeau** [comment]
After running `yarn analyze`, if you go to http://localhost:3031/ locally, you should see it. For example, here's the diff for lodash:

**Before**:
Screenshot from 2020-10-22 13-44-03
Screenshot from 2020-10-22 13-43-58

**After**:
Screenshot from 2020-10-22 13-28-00
Screenshot from 2020-10-22 13-29-21

**Review by BenJeau — APPROVED** [review]

**Comment by mo-5** [comment]
Oh cool thank you

**Pull request merged**
