### PR TITLE
[New] Add print button to profiles

### LINKED ISSUE #215: Add "Print results" button to results page
**Is your feature request related to a problem? Please describe.**
Some managers may want to a physical copy of all resumes of the employees that match their search results, thus we need a way to easily print them out.

**Describe the solution you'd like**
A button on the results page/in the results page sidebar that prints nicely formated resumes (sumaries of the profile page) of each applicant that matched the search criteria/is displayed on the results page.

### PR DESCRIPTION
**Pull request by mo-5**
#### Changes introduced

I added a print button to allow users to print their profile and other users' profile. Please note I removed the private connections list from the print that way the list remains private. 

There is one issue with this is that sometimes the cards cut and continue on the next page. Unfortunately, there is no good way to fix this since the cards are variable to the amount of information the user provides. 

#### Related issue(s)

closes #215

#### Screenshots (if applicable)

button location:
image
once you click on the button:
image
example:
image

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

### CODE REVIEW

**Comment by dynamic11** [comment]
As seen in the image below the skills are all collapsed. I don't think this is very helpful. we can either expand it on print or generate a CSV/excel. I'm personally team CSV/Excel because it condenses the info and saves paper 😛 .

image

**Comment by mo-5** [comment]
I think we could expand them on the print I would have to look more into it. There is a way we could create a pdf or csv/excel file instead of just a print screen but we would need to install another package.

**Comment by mo-5** [comment]
I updated skills and mentorship to this. Since it is the only way to make them expand during command. Chrome stopped supporting event handlers during printing. 

profile:
image

print:
image



I have done this we will limit the number of skills a user can add to their profile. Please let me know if this will be okay.

**Comment by mo-5** [comment]
image

**Review by Rizvida1 — APPROVED** [review]

**Pull request merged**
